# CI-Pipeline.yml
trigger:
  branches:
    include:
      - '*'    # Run on pushes to any branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout repository'

# Install the NuGet tool for package management.
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>=5.0.0'
  displayName: 'Install NuGet Tool'

# Authenticate to Azure Artifacts to access packages from the AutomatedTesting feed.
- task: NuGetAuthenticate@0
  displayName: 'Authenticate to Azure Artifacts'

# Install the .NET 6 SDK on the agent.
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: false
  displayName: 'Install .NET 6 SDK'

# Restore NuGet packages using DotNetCoreCLI@2.
# Note: On the Ubuntu agent, use the relative path "Tests/nuget.config" (not the Windows absolute path).
# Restore NuGet packages using DotNetCoreCLI@2.
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: 'Tests/Tests.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'Tests/nuget.config'

- script: |
    echo "Listing restored NuGet packages..."
    dotnet list Tests/Tests.sln package --include-transitive
  displayName: 'List restored NuGet packages'

# Build the solution in Release configuration (skip restore since it’s already done).
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: 'Tests/Tests.sln'
    arguments: '--configuration Release --no-restore'

# Run tests using DotNetCoreCLI@2 and output the results in TRX format.
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'Tests/Tests.sln'
    arguments: '--configuration Release --no-build --logger "trx;LogFileName=test_results.trx"'

# Publish test results to Azure DevOps for visualization in the build summary.
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/test_results.trx'
    mergeTestResults: true
