trigger:
  branches:
    include: [ main ]

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.0.x'

stages:
- stage: Build_Test
  jobs:
  - job: BuildTest
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(dotnetVersion)

    - script: dotnet restore Tests/Tests.sln --locked-mode
      displayName: dotnet restore

    - script: dotnet build Tests/Tests.sln --configuration $(buildConfiguration) --no-restore --property:ContinuousIntegrationBuild=true
      displayName: dotnet build

    # 🔍 NEW: List every JSON / config copied to output folder
    - script: |
        echo "=== Copied runtime assets (json / config) ==="
        find Tests -path '*/bin/$(buildConfiguration)/*' \
             \( -name '*.json' -o -name '*.config' \) -print | sort
      displayName: verify copied files
      condition: always()

    - script: |
        dotnet test Tests/Tests.sln \
          --configuration $(buildConfiguration) \
          --no-build \
          --logger trx \
          --collect:"XPlat Code Coverage"
      displayName: dotnet test

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
        failTaskOnFailedTests: true

    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        reportDirectory: '$(Agent.TempDirectory)'
